import type { Metadata } from "next";
import localFont from "next/font/local";
import {Poppins} from 'next/font/google';
import "./globals.css";
import HeroSection from "@/components/Nav";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";

const poppins_init = Poppins({
  subsets: ["latin"],
  weight: ['100', '300', '700'],
  variable: '--font-poppins'
});




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
          <Nav/>
        {children}
      
        {children}
        <Footer />
      </body>
    </html>
  );
}
